#!/bin/bash

echo "🚀 GPS Field Tracker Distribution Helper"
echo "========================================"

echo ""
echo "📱 SHARE THESE LINKS WITH YOUR FIELD TEAMS:"
echo ""

echo "🔗 Direct APK Download:"
echo "https://github.com/jonobenjamin/WildlifeTracker/releases/latest/download/GPS-Field-Tracker-v3.0.0.apk"
echo ""

echo "🌐 Professional Download Page:"
echo "https://jonobenjamin.github.io/WildlifeTracker/download.html"
echo ""

echo "📚 Full Documentation:"
echo "https://github.com/jonobenjamin/WildlifeTracker"
echo ""

echo "📋 QUICK INSTALLATION INSTRUCTIONS:"
echo "=================================="
echo ""
echo "1. Click the APK download link above"
echo "2. Save the APK file to your Android phone"
echo "3. Open the APK file"
echo "4. Enable 'Install unknown apps' if prompted"
echo "5. Tap 'Install' and follow the prompts"
echo "6. Open 'GPS Field Tracker' from your app drawer"
echo ""
echo "7. First-time setup:"
echo "   - Tap Settings (⚙️)"
echo "   - Create GitHub token: https://github.com/settings/tokens"
echo "   - Give token 'repo' permissions"
echo "   - Enter token and repository name in app"
echo "   - Start collecting GPS data!"
echo ""

echo "📊 DATA STORAGE:"
echo "==============="
echo "Each GPS observation saves as JSON to your GitHub repository:"
echo "📁 Repository: your-github-username/your-repo-name"
echo "📂 Folder: data/ (or custom folder you specify)"
echo "📄 Files: observation_[timestamp].json"
echo ""

echo "🔄 UPDATES:"
echo "==========="
echo "The app checks for updates automatically."
echo "New versions will be available at the same download links."
echo ""

echo "📞 SUPPORT:"
echo "=========="
echo "If users need help:"
echo "- Check the app's built-in help"
echo "- Visit: https://jonobenjamin.github.io/WildlifeTracker/download.html"
echo "- Repository: https://github.com/jonobenjamin/WildlifeTracker"
echo ""

echo "✅ READY TO DISTRIBUTE!"
echo "======================"
echo "Send your field teams the APK download link above."
echo "They can install and start collecting GPS data immediately!"