#!/bin/bash

echo "🚀 GPS Field Tracker Distribution Helper"
echo "========================================"

echo ""
echo "📱 SHARE THESE LINKS WITH YOUR FIELD TEAMS:"
echo ""

echo "🌐 GPS Field Tracker Web App:"
echo "https://jonobenjamin.github.io/WildlifeTracker/"
echo ""

echo "📱 Professional Download Page:"
echo "https://jonobenjamin.github.io/WildlifeTracker/download.html"
echo ""

echo "📚 Full Documentation:"
echo "https://github.com/jonobenjamin/WildlifeTracker"
echo ""

echo "📋 QUICK INSTALLATION INSTRUCTIONS:"
echo "=================================="
echo ""
echo "1. Open the web app link above on your phone"
echo "2. Tap 'Add to Home Screen' or 'Install App'"
echo "3. The app installs like a native mobile app!"
echo "4. Open GPS Field Tracker from your home screen"
echo ""
echo "7. First-time setup:"
echo "   - Tap Settings (⚙️)"
echo "   - Create GitHub token: https://github.com/settings/tokens"
echo "   - Give token 'repo' permissions"
echo "   - Enter token and repository name in app"
echo "   - Start collecting GPS data!"
echo ""

echo "📊 DATA STORAGE:"
echo "==============="
echo "Each GPS observation saves as JSON to your GitHub repository:"
echo "📁 Repository: your-github-username/your-repo-name"
echo "📂 Folder: data/ (or custom folder you specify)"
echo "📄 Files: observation_[timestamp].json"
echo ""

echo "🔄 UPDATES:"
echo "==========="
echo "The app checks for updates automatically."
echo "New versions will be available at the same download links."
echo ""

echo "📞 SUPPORT:"
echo "=========="
echo "If users need help:"
echo "- Check the app's built-in help"
echo "- Visit: https://jonobenjamin.github.io/WildlifeTracker/download.html"
echo "- Repository: https://github.com/jonobenjamin/WildlifeTracker"
echo ""

echo "✅ READY TO DISTRIBUTE!"
echo "======================"
echo "Send your field teams the web app link above."
echo "They can install and start collecting GPS data immediately!"